import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import type { FailureReport } from "./types.ts";
import { groupByCategory } from "./classifier.ts";

const GRADIENT_BASE = "https://inference.do-ai.run/v1";
const MODEL = "llama3.3-70b-instruct";

function buildGradientPrompt(report: FailureReport): string {
    const groups = groupByCategory(report.classified);

    const categorySummary = Object.entries(groups)
        .map(([cat, lines]) => {
            const sample = (lines ?? [])
                .slice(0, 5)
                .map((l) => `  • ${l.line}`)
                .join("\n");
            return `**${cat}** (${(lines ?? []).length} matching lines)\n${sample}`;
        })
        .join("\n\n");

    const stepsSummary = report.failedSteps
        .slice(0, 10)
        .map(
            (s) =>
                `  - Step "${s.name}" [${s.status}]: ${s.reason?.message ?? s.message_base ?? "no message"}`
        )
        .join("\n");

    const exitSummary = Object.entries(report.exitCodes)
        .map(([name, code]) => `  - ${name}: exit ${code}`)
        .join("\n");

    const filesList = report.affectedFiles.length
        ? report.affectedFiles.map((f) => `  - ${f}`).join("\n")
        : "  (none detected from logs)";

    return `You are an expert DevOps / software engineer.
A DigitalOcean App Platform deployment has FAILED.

## Deployment Info
- ID: ${report.deployment.id}
- Phase: ${report.deployment.phase}
- Cause: ${report.deployment.cause}
- Updated: ${report.deployment.updated_at}

## Log Classification Summary
${categorySummary || "(no classified lines)"}

## Failed Build / Deploy Steps
${stepsSummary || "(none)"}

## Exit Codes
${exitSummary || "(none)"}

## Files Referenced in Logs
${filesList}

## Task
Generate a comprehensive, actionable prompt that a developer can paste DIRECTLY into an AI coding assistant (such as Cursor, GitHub Copilot Chat, Kilo, or Windsurf). The prompt must:

1. Instruct the AI agent to open and inspect EVERY file listed above that is likely related to the failure.
2. Guide it to check each of the detected error categories in those files.
3. Ask it to look at the project's package.json / tsconfig / Dockerfile / .env.* / Dockerfile for misconfigurations.
4. Ask it to trace the root cause and propose a concrete fix with code diffs or specific lines to change.
5. Be written in second-person (you / your) so it reads naturally when pasted.
6. Be self-contained: include enough context about the error categories, file list, and failure phase so the AI can work without additional context.

Output ONLY the final prompt text. Do not add any explanation or wrapper text around it.`;
}

interface GradientMessage {
    role: "system" | "user" | "assistant";
    content: string;
}

interface GradientResponse {
    choices: Array<{ message: GradientMessage }>;
}

async function callGradientAI(
    userPrompt: string,
    token: string
): Promise<string> {
    const messages: GradientMessage[] = [
        {
            role: "system",
            content:
                "You are a senior DevOps engineer generating structured debugging prompts for AI coding assistants.",
        },
        { role: "user", content: userPrompt },
    ];

    const res = await fetch(`${GRADIENT_BASE}/chat/completions`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            model: MODEL,
            messages,
            max_tokens: 2048,
            temperature: 0.3,
        }),
    });

    if (!res.ok) {
        const body = await res.text();
        throw new Error(
            `[PromptBuilder] Gradient AI ${res.status} ${res.statusText}: ${body}`
        );
    }

    const data = (await res.json()) as GradientResponse;
    const content = data.choices[0]?.message?.content ?? "";
    return content.trim();
}

function savePromptFile(prompt: string, outputDir: string): string {
    mkdirSync(outputDir, { recursive: true });
    const filePath = join(outputDir, "prompt.md");
    const header = `# Deployment Failure — AI Agent Prompt\n\n> Auto-generated by \`failure_check\` service on ${new Date().toISOString()}\n\n---\n\n`;
    writeFileSync(filePath, header + prompt, "utf-8");
    return filePath;
}

export async function buildAndSavePrompt(
    report: FailureReport,
    gradientToken: string,
    outputDir: string = "."
): Promise<string> {
    console.log("[PromptBuilder] Calling DO Gradient AI to generate prompt…");

    const gradientInput = buildGradientPrompt(report);
    const generatedPrompt = await callGradientAI(gradientInput, gradientToken);

    const filePath = savePromptFile(generatedPrompt, outputDir);
    console.log(`[PromptBuilder] ✓ Prompt saved to: ${filePath}`);
    return filePath;
}
